spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    虚拟机数据库
    url: jdbc:mysql://10.130.3.23/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 8080